import Foundation

/// A codable wrapper for the acknowledgments JSON manifest generated by the build plugin.
public struct AcknowledgmentsManifest: Codable, Sendable {
    /// The list of acknowledgment entries in this manifest.
    public let acknowledgments: [Acknowledgment]

    public init(acknowledgments: [Acknowledgment]) {
        self.acknowledgments = acknowledgments
    }

    /// Decodes a manifest from JSON data.
    public static func decode(from data: Data) throws -> AcknowledgmentsManifest {
        let decoder = JSONDecoder()
        return try decoder.decode(AcknowledgmentsManifest.self, from: data)
    }
}
